install.packages("ggplot2")
library(ggplot2)
View(mpg)
ggplot(data=mpg)
ggplot(data=mpg)+aes(x=displ,y=hwy)
ggplot(data=mpg)+aes(x=displ,y=hwy)+geom_point()
ggplot(data=mpg)+aes(x=displ,y=hwy)+geom_point()+geom_smooth()
ggplot(data=mpg)+aes(x=displ,y=hwy, color=class, shape=factor(cyl))+geom_point()
ggplot(data=mpg)+aes(x=displ,y=hwy,color=class)+geom_point()+facet_wrap(~cyl)
ggplot(data=mpg)+aes(x=hwy)+geom_histogram()
